# -*- coding: utf-8 -*-
"""terremoto.ipynb

Automatically generated by Colab.



## **Análise Visual dos Terremotos Globais (1965-2016): Distribuição, Magnitude e Padrões Temporais**

# Inicialização / Pré-Processamento
"""

import pandas as pd
import plotly.express as px


df = pd.read_csv("database.csv")

colunas = ['Date', 'Time', 'Latitude', 'Longitude', 'Type', 'Depth', 'Magnitude']
df = df[colunas]


df['Date'] = df['Date'].str.replace('-', '/', regex=False)
df = df[~df['Date'].str.contains(':', na=False)]

df = df[df['Type'] == 'Earthquake']

df['Date'] = pd.to_datetime(df['Date'], format='%m/%d/%Y')
df['Date'] = df['Date'].dt.year
df = df.rename(columns={'Date': 'Year'})


df['Time'] = pd.to_datetime(df['Time'], format='%H:%M:%S')

# Extraindo apenas a hora
df['Time'] = df['Time'].dt.hour
df = df.rename(columns={'Time': 'Hour'})



"""#Mapa de Distribuição Geográfica dos Terremotos"""

df_sample = df.sample(frac=0.2, random_state=1)

fig = px.scatter_mapbox(
    df_sample,
    lat="Latitude",
    lon="Longitude",
    color="Magnitude",
    color_continuous_scale=[
        (0.00, "#ffcc00"), (0.25, "#ffcc00"),
        (0.25, "#fc9e0f"), (0.5, "#fc9e0f"),
        (0.5, "#ff2a00"), (0.75, "#ff2a00"),
        (0.75, "#4d0202"), (1.00, "#4d0202")
    ],
    color_continuous_midpoint=6.5,
    title="Distribuição Geográfica dos Terremotos",
    mapbox_style="open-street-map",
    width=1400,
    height=600,
    zoom=1.5
)

fig.update_layout(
    title=dict(
        text="Distribuição Geográfica dos Terremotos",
        font=dict(size=22, color="#000000", family="Arial, sans-serif",),
        x=0.5,
        xanchor='center',
    )
)

fig.update_traces(marker=dict(size=9, opacity=0.6))


fig.show()

"""#Distribuição de Magnitudes dos Terremotos por Ano

"""

fig = px.box(df, x="Year", y="Magnitude",
             title="Distribuição de Magnitudes dos Terremotos por Ano",
             labels={"Year": "Ano", "Magnitude": "Magnitude"},
             color_discrete_sequence=["#4d0202"],
             width=1300, height=500)

fig.update_layout(plot_bgcolor="#f0f0f0")

fig.update_layout(
    title=dict(
        text="Distribuição de Magnitudes dos Terremotos por Ano",
        font=dict(size=22, color="#000000", family="Arial, sans-serif",),
        x=0.5,
        xanchor='center',
    )
)
fig.show()

"""#Profundidade Média dos Terremotos ao Longo dos Anos

"""

df_depth_by_year = df.groupby("Year")["Depth"].mean().reset_index()

fig = px.line(df_depth_by_year, x="Year", y="Depth",
              title="Profundidade Média dos Terremotos ao Longo dos Anos",
              labels={"Year": "Ano", "Depth": "Profundidade Média (km)"},
              color_discrete_sequence=["#4d0202"],
              width=1300, height=500)

fig.update_layout(plot_bgcolor="#f0f0f0")

fig.update_layout(
    title=dict(
        text="Profundidade Média dos Terremotos ao Longo dos Anos",
        font=dict(size=22, color="#000000", family="Arial, sans-serif",),
        x=0.5,
        xanchor='center',
    )
)
fig.show()

"""#Frequência de Terremotos por Ano"""

fig = px.line(df[df['Type'] == 'Earthquake'].groupby('Year').size().reset_index(name='Frequência'),
               x='Year', y='Frequência',
               labels={"Year": "Ano", "Frequência":"Frequência"},
               title='Frequência de Terremotos por Ano',
               color_discrete_sequence=["#4d0202"],
               width=1300, height=500)


fig.update_layout(plot_bgcolor="#f0f0f0")

fig.update_layout(
    title=dict(
        text="Frequência de Terremotos por Ano",
        font=dict(size=22, color="#000000", family="Arial, sans-serif",),
        x=0.5,
        xanchor='center',
    )
)

fig.show()

"""#Frequência Total de Terremotos por Hora do Dia"""

hour_counts = df['Hour'].value_counts().reset_index(name='Count')
hour_counts.columns = ['Hour', 'Count']
hour_counts = hour_counts.sort_values(by='Hour')
hour_counts['Hora'] = hour_counts['Hour'] * (360 / 24)
hour_0 = hour_counts[hour_counts['Hour'] == 0].iloc[0]
hour_counts = pd.concat([hour_counts, pd.DataFrame([hour_0])], ignore_index=True)

fig = px.line_polar(hour_counts, r="Count", theta="Hora", markers=True,
                    title="Frequência Total de Terremotos por Hora do Dia",
                    labels={"Hour": "Hora do Dia", "Count": "Frequência"},
                    color_discrete_sequence=["#4d0202"],
                    width=1300, height=500)

fig.update_traces(fill='toself')

fig.update_layout(
    polar=dict(
        bgcolor="#f0f0f0",
        angularaxis=dict(
            tickvals=[i * (360 / 24) for i in range(0, 24)],
            ticktext=[f'{i}:00' for i in range(0, 24)]
        ),
        radialaxis=dict(
            visible=True,
            range=[500, 1100],
            tickfont=dict(color="#000000", size=14),
            linecolor="#4d0202"
        )
    ),
    title=dict(
        text="Frequência Total de Terremotos por Hora do Dia",
        font=dict(size=22, color="#000000", family="Arial, sans-serif"),
        x=0.5,
        xanchor='center',
    ),
)

fig.show()